### ISSUE TITLE
There is no way to abort the installation

### ISSUE THREAD

**Issue by kobliha** [openSUSE/agama#1059] opened 2024-02-28 16:14 UTC
Let's say I've just decided not to install the machine now. What should I do to abort the installation? The user might not know if anything is mounted or so, pushing the power button might be possible, but maybe not safe? What about for remote installations?

Yes, I know I can halt it from the cmdline, but it's really not so obvious.

**Comment by kobliha** [comment] 2024-03-06 14:30
As a workaround, it's possible to open a console and use `halt` or `reboot`, but obviously the point is that the user does not know about it (most probably) and also does not know whether it's safe (it is, most probably ;)).

**Comment by ancorgs** [comment] 2024-05-17 10:34
Well, I would say this is a duplicate of https://github.com/openSUSE/agama/issues/561

**Comment by imobachgs** [comment] 2024-06-13 11:21
Yes, I would say it is a duplicate.

**Closed by imobachgs** 2024-06-13 11:21 UTC
