### ISSUE TITLE
Improve mount point selector

### ISSUE THREAD

**Issue by joseivanlopez** [openSUSE/agama#932] opened 2023-12-15 16:01 UTC
When editing a file system, the form shows a disabled selector for the mount point field. Using a disabled widget does not make sense in this case because the mount point will never be editable. The disabled widget should be replaced by plain text.

Moreover, the selector currently uses a `FormSelect` component. It should be replaced by the `Select` component, similar to the file system type selector.

* https://github.com/openSUSE/agama/blob/master/web/src/components/storage/VolumeForm.jsx#L76

![localhost_8080_(iPad Mini) (21)](https://github.com/openSUSE/agama/assets/1112304/91a87f6a-a687-4ce2-a09b-cf0ed26300c1)

**Comment by itsrajshivhare** [comment] 2023-12-18 06:41
Hi @joseivanlopez, I would like to work on the issue.

**Comment by joseivanlopez** [comment] 2023-12-18 08:53
> Hi @joseivanlopez, I would like to work on the issue.

Sure, go ahead with a pull request. Do you need help to start moving on? Thanks a lot!

**Comment by itsrajshivhare** [comment] 2023-12-18 10:35
Thank you @joseivanlopez   for your quick response! I'm eager to get started on contributing to the project.

**Comment by itsrajshivhare** [comment] 2023-12-18 13:32
Hi @joseivanlopez, Apologies for reaching out at this moment. I'm facing challenges while setting up the project, encountering errors like "Cannot connect to the Cockpit server" (attached the photos for reference). Since I'm new to this, I would greatly appreciate your guidance and assistance.
![Screenshot (211)](https://github.com/openSUSE/agama/assets/86731044/9359ce8e-9913-4139-ab04-3ea1fd4ed7ca)
![Screenshot (212)](https://github.com/openSUSE/agama/assets/86731044/9b7f08f4-a303-4e74-aea7-279dcd92ecd7)
Thanks for your understanding.

**Comment by itsrajshivhare** [comment] 2023-12-18 13:33
Hi @joseivanlopez, Apologies for reaching out at this moment. I'm facing challenges while setting up the project, encountering errors like "Cannot connect to the Cockpit server" (attached the photos for reference). Since I'm new to this, I would greatly appreciate your guidance and assistance.
![Screenshot (34)](https://github.com/openSUSE/agama/assets/86731044/ba23a9a5-b638-4427-94d9-24c5e84123e9)
![Screenshot (35)](https://github.com/openSUSE/agama/assets/86731044/c48f88f6-b570-44fb-a4c7-a72fb9bd38e5)
Thanks for your understanding.

**Comment by joseivanlopez** [comment] 2023-12-19 15:42
For running Agama you need to start both the Agama services (backend) and the web UI. Are you running the Agama services?

I would suggest to create a virtual machine and use it to run our [live iso image](https://github.com/openSUSE/agama?tab=readme-ov-file#live-iso-image).

Once the Agama live image is booted in your virtual machine, you can run the web UI from your git clone:

~~~
$ git clone https://github.com/openSUSE/agama
$ cd agama
$ COCKPIT_TARGET=<virtual-machine-ip> npm run server
~~~

Please, try it and let me know if it works. If not, we can try another approach. Thanks!

**Comment by nagu165** [comment] 2023-12-27 16:37
Hey, I am working on this issue and I don't completely understand the first part you mentioned and am stuck on how to proceed there
And I also wanted your suggestion on making pull requests for minute changes that you mentioned in the second part (changing from formSelect to Select) without moving forward with the first part of the issue.
Thank you for the understanding.

**Comment by dgdavid** [comment] 2023-12-28 09:28
> Hey, I am working on this issue and 

Hi @nagu165, thanks a lot and welcome aboard!

> I don't completely understand the first part you mentioned and am stuck on how to proceed there 

It's actually simple, the `MountPointFormSelect` at `components/storage/VolumeForm.jsx` should not be mounted when editing a volume. Instead, the mount point should be rendered as plain text (a.k.a.) string.

However, I admit that `VolumesForm` component could be a bit overwhelming at first sight, depending on your development background. So, don't worry and skip that part of the issue to make your first contribution and get familiar with the code.

> And I also wanted your suggestion on making pull requests for minute changes that you mentioned in the second part (changing from formSelect to Select) without moving forward with the first part of the issue. 

Just go ahead and open the PR if you have the change ready. During the code review we are gonna make suggestions and help you to move it on. The only thing I can suggest at this time is to make atomic, self-explanatory commits and to try to not forget about the tests :innocent:  but if you have doubts, just open the PR and let's work on it together.

> Thank you for the understanding.

Anytime!  It's our pleasure to help you to make a contribution to Agama... and try to keep you engaged :stuck_out_tongue_winking_eye:

**Comment by rohit9625** [comment] 2023-12-29 16:27
Hello @dgdavid sir, I tried setting up the local environment and reached the login page of Agama. But for username - root and password - Linux, it's showing the wrong username or password.

**Comment by nagu165** [comment] 2023-12-30 07:20
hello sir, I am trying to setup the project using the virtualBox and was confused on which version of linux to select here
![Screenshot 2023-12-30 124643](https://github.com/openSUSE/agama/assets/125825782/d9910b16-5f62-438a-86fc-a282ff696d7f)
and also wanted to ask u whether for the second part of the issue is this all u want (attached the screenshot) or else if anything is missing please do let me know
![Screenshot 2023-12-30 124456](https://github.com/openSUSE/agama/assets/125825782/bb43a1c6-ef11-4dbf-8b03-cfbe69adacfe)
Thank you

**Comment by dgdavid** [comment] 2023-12-30 10:44
> Hello @dgdavid sir, 

Hi @rohit9625

> I tried setting up the local environment and reached the login page of Agama. But for username - root and password - Linux, it's showing the wrong username or password.

`root`/`linux` is the user password for the [Agama live ISOs](https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/). If you have set the environment in your own machine, the user and password are these you normally use for login into the system. PLEASE, be careful if you are doing so. My recomendation is to [use a virtual machine](https://github.com/openSUSE/agama#live-iso-image) for contributing to this project if you are not completely sure what you're doing.

**Comment by dgdavid** [comment] 2023-12-30 10:55
> hello sir, I am trying to setup the project using the virtualBox and was confused on which version of linux to select here 

I'd choose openSUSE Tumbleweed (64-bit)

>  and also wanted to ask u whether for the second part of the issue is this all u want

Please, just open the PR if you don't mind. Making a _picture-driven review_ is not the way we work. It will require a lot of effort from our side and, honestly, will be a full mess. Moreover, we have set some automated check that help with the process by running linters and test suite. So, don't be shy and go ahead with the PR once you have everything in place: changes in the code, tests up-to-date, and ideally you have checked it manually too. From that point on, the YaST team could help you to move it on by making needed suggestions.

> Thank you

Thanks to you for the time invested on contributing to Agama.

**Comment by nagu165** [comment] 2024-01-07 14:04
Hello sir, Really sorry for the trouble but I needed a little clarification on the issue.
From what I understood by reading the code and test cases and @dgdavid sir's suggestion, I am assuming that when currentVolume is defined we need to show a text describing which volume was selected for mounting and when currentVolume is undefined we need to let the user select the volume from the list of volume templates where we will proceed with the installation right?. But when we replace the selector with the text the test cases suggest( I think ) that they need to find mountpointformselect component ( as combobox ). 
I seem to have fixed the issue but when running the tests it's showing some errors, could you please provide a hint on where I might be wrong. 
![Screenshot (8)](https://github.com/openSUSE/agama/assets/125825782/e23733a8-2d03-49e6-9095-8cf9bfa3e7dd)
Thank you so much.

**Comment by dgdavid** [comment] 2024-01-08 09:18
> Hello sir, Really sorry for the trouble but I needed a little clarification on the issue. From what I understood by reading the code and test cases and @dgdavid sir's suggestion, I am assuming that when currentVolume is defined we need to show a text describing which volume was selected for mounting and when currentVolume is undefined we need to let the user select the volume from the list of volume templates where we will proceed with the installation right?.

That's right.


> But when we replace the selector with the text the test cases suggest( I think ) that they need to find mountpointformselect component ( as combobox ). I seem to have fixed the issue but when running the tests it's showing some errors, could you please provide a hint on where I might be wrong. 

Quite expected. Tests must be updated to the new behavior too. Do you need help understanding and updating the VolumeForm.test.jsx?

**Comment by dgdavid** [comment] 2024-01-08 09:26
> 
> Quite expected. Tests must be updated to the new behavior too. Do you need help understanding and updating the VolumeForm.test.jsx?

Thinking it twice, maybe we can collaborate in this first contribution for speeding up the PR and continue helping you to get familiar with both, the Agama project and React Testing Library. The idea is that you can update the PR with changes done in `VolumeForm.jsx` and I'll update the test. Then, you can read my changes and ask anything it's not clear for your or even give us your feedback/review about these changes.

Once we have it ready, you should add the entry in the changes file and finally we can go ahead by merging your first contribution to Agama.

What do you think?

**Comment by nagu165** [comment] 2024-01-22 16:26
Hello sir, This issue was solved with the PR 1007. And really sorry for asking like this but could you assign some small bugs to me that were not yet mentioned in the issues section I am a beginner and the current issues seem either too difficult or of some technology I don't know yet.

Thank you.

**Comment by dgdavid** [comment] 2024-01-24 14:18
Hey @nagu165, 

Right, this issue can be closed now. Thanks for the reminder.

In regard to looking for a small issue, while it's true I told you we can do it, sadly it is also a fact that I'm a bit busy at this moment helping the team to move a bunch of things on. I do not know when exactly I could take a break for creating well-defined good-first-issues. Maybe at the end of the second week of February.

However, I really appreciate your interest in the project and I wouldn't like to lose your willingness to help here :) So, I'd like to encourage you to contribute differently until you/we find a task you can tackle: by providing feedback. The idea is simple, you can go through the Agama UI and give us your feedback from the user perspective, especially what you find confusing or difficult to understand. I know, at first sight it can look boring or not interesting from a developer perspective, but believe me: it would be a great contribution and even a good learning opportunity since you can go through the related source code for having the complete picture before opening an issue or discussion.

Also, you can check open PRs (like [this one I'm working on](https://github.com/openSUSE/agama/pull/1012)) and, apart from learning something from them, make suggestions or ask questions about the code before it gets merged.

Last but not least, you can also give us your view in open [discussions](https://github.com/openSUSE/agama/discussions), or even open a new one.

But they are just ideas for contributing without the need of making a PR for solving a specific issue. Of course, you can simply wait until we create more issues and find one that suits your expectations. Or maybe someone inside the @openSUSE/yast team have a clear idea of something small for you this week.

What do you think?

Regards.

**Closed** 2024-01-24 14:18 UTC
Labels: enhancement, good first issue

**Comment by imobachgs** [comment] 2024-01-24 15:48
Hi @nagu165,

As @dgdavid we are reorganizing some things but we plan to come up with some good first issues in a few weeks. Contributing to a project is not just writing code but giving feedback, opening issues, etc. We appreciate that 😉 

However, if you want to try some coding, you could give issue #860 a try. What do you think?

**Comment by nagu165** [comment] 2024-01-26 17:28
> Hey @nagu165,
> 
> Right, this issue can be closed now. Thanks for the reminder.
> 
> In regard to looking for a small issue, while it's true I told you we can do it, sadly it is also a fact that I'm a bit busy at this moment helping the team to move a bunch of things on. I do not know when exactly I could take a break for creating well-defined good-first-issues. Maybe at the end of the second week of February.
> 
> However, I really appreciate your interest in the project and I wouldn't like to lose your willingness to help here :) So, I'd like to encourage you to contribute differently until you/we find a task you can tackle: by providing feedback. The idea is simple, you can go through the Agama UI and give us your feedback from the user perspective, especially what you find confusing or difficult to understand. I know, at first sight it can look boring or not interesting from a developer perspective, but believe me: it would be a great contribution and even a good learning opportunity since you can go through the related source code for having the complete picture before opening an issue or discussion.
> 
> Also, you can check open PRs (like [this one I'm working on](https://github.com/openSUSE/agama/pull/1012)) and, apart from learning something from them, make suggestions or ask questions about the code before it gets merged.
> 
> Last but not least, you can also give us your view in open [discussions](https://github.com/openSUSE/agama/discussions), or even open a new one.
> 
> But they are just ideas for contributing without the need of making a PR for solving a specific issue. Of course, you can simply wait until we create more issues and find one that suits your expectations. Or maybe someone inside the @openSUSE/yast team have a clear idea of something small for you this week.
> 
> What do you think?
> 
> Regards.

Thank you for the response sir, I will look through the project as you have mentioned.

**Comment by nagu165** [comment] 2024-01-26 17:28
> Hi @nagu165,
> 
> As @dgdavid we are reorganizing some things but we plan to come up with some good first issues in a few weeks. Contributing to a project is not just writing code but giving feedback, opening issues, etc. We appreciate that 😉
> 
> However, if you want to try some coding, you could give issue #860 a try. What do you think?

Thank you sir, I will try my best.
