### ISSUE TITLE
Improve form errors

### ISSUE THREAD

**Issue by joseivanlopez** [openSUSE/agama#468] opened 2023-03-16 13:36 UTC
We have forms informing about errors when something is wrong after submitting the form. Generally, the errors are shown at the top of the form. The problem is when you click on submit again and you get the error again. Visually nothing changes and it seems the submit button is doing nothing.

**Comment by Anandpandey0** [comment] 2023-04-28 06:57
I can do this. Please assign it to me.

**Comment by joseivanlopez** [comment] 2023-04-28 09:40
Great! Please, simply go ahead by creating a PR. Thanks!

**Comment by balsa-asanovic** [comment] 2023-07-21 21:16
Hey, I'd be interested in working on this.

However, could you provide me with some additional details/screenshots about this issue?

Thanks

**Comment by joseivanlopez** [comment] 2023-07-26 11:06
For example, if you go to Storage -> iSCSI. Try to discover targets.

![localhost_8080_ (15)](https://github.com/openSUSE/agama/assets/1112304/92b0a45c-1998-408e-bfd9-e5646c869eb7)

After submiting, you get an error message at top (if it fails):

![localhost_8080_ (16)](https://github.com/openSUSE/agama/assets/1112304/e7ecd11e-47db-4e79-ba85-1fd6fc8b855b)

And note that after submitting, the form does not scroll up.

![localhost_8080_ (17)](https://github.com/openSUSE/agama/assets/1112304/e4279a34-9f10-4d3d-bd42-0ebb64317526)

So it is difficult to realize whether it failed again. So, maybe we need to scroll-up and somehow highlight the error again. But that is only an idea.

The goal is to improve UX but making more evident that the form failed again. Please, discuss any proposal you have in mind before going ahead with the implementation.

Thanks!

**Comment by balsa-asanovic** [comment] 2023-08-10 23:00
Hey @joseivanlopez ,

Thanks for the detailed explanation, that helped a lot.

To me the scroll up seems like a reasonable solution.

I've introduced these changes in PR #699, so you can check it out.

Also, I wasn't sure, but maybe a good idea would be to make the alert invisible again on any change of the input fields in the form.
What do you think about this?

Because, when the form has no scrollbar (the full component can fit on the screen) it seems as if the error warning is just stuck. If it disappears on any data change and then reappears on submit (if the issue is still present), seems like a possibly better experience for the user.

**Comment by imobachgs** [comment] 2023-08-11 08:29
To be honest, I am not sure if auto-scrolling is the best solution. I think we should think better about form designs in general. But for now, it solves the original problem, so I am happy with it. :-)

About making the message invisible, I do not have a strong opinion.

**Closed** 2023-08-12 17:20 UTC
Labels: enhancement, ux
