### ISSUE TITLE
Network connection issues

### ISSUE THREAD

**Issue by bittin** [openSUSE/agama#1019] opened 2024-01-27 08:13 UTC
Hi!

Could not connect to any networks with the latest iso: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-live.x86_64-openSUSE.iso using Virtualbox to try it out

**Comment by imobachgs** [comment] 2024-01-29 06:39
The cause of the problem the #998 issue. For some reason, the Python-based bridge is included in the ISO. The same applies to #1018.

**Comment by imobachgs** [comment] 2024-01-29 07:10
Fixed in build 4.14. Thanks!

**Closed by imobachgs** 2024-01-29 07:10 UTC
